---
- name: SHOW CONFIG
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
    - name: RUN show version on remote devices
      ios_command:
        commands: show version

    - name: RUN show version and check to see if output contains IOS
      ios_command:
        commands: show version
        wait_for: result[0] contains IOS

    - name: RUN multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show interfaces

    - name: RUN multiple commands and evaluate the output
      ios_command:
        commands:
          - show version
          - show interfaces
        wait_for:
          - result[0] contains IOS
          - result[1] contains Internet

    - name: RUN commands that require answering a prompt
      ios_command:
        parents: "interface GigabitEthernet1"
        commands:
          - command: 'clear counters GigabitEthernet1'
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: 'y'
